// <auto-generated />
using System;
using Database.Entitys;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20231230130339_uodateData")]
    partial class uodateData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Database.Entitys.TbConfiguration", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("TbConfiguration");
                });

            modelBuilder.Entity("Database.Entitys.TbContent", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentId"), 1L, 1);

                    b.Property<string>("ContentBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ContentId");

                    b.ToTable("TbContent");
                });

            modelBuilder.Entity("Database.Entitys.TbFile", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FileId");

                    b.ToTable("TbFile");

                    b.HasData(
                        new
                        {
                            FileId = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_29_AHA-and-BHA-2__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_28_BC2NEW__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 3,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_12_BC2-BOX__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_8_Flawless-Facial-Toner-2__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 5,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_18_bc1-box__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 6,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_30_BC3-GOOD__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 7,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_58_BC3-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 8,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_19_BU6Goldfusioncleansingoil__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 9,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_65_BC8NEW__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 10,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_123_BC8-NEW-BOX-2023__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 11,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_4_BN3__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 12,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_43_BN3-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 13,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_5_Collagen-Infused-Day-Cream__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 14,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_60_BN1-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 15,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_6_BN7__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 16,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_111_BN6-TRANSFORMED-FROM-BN7-BOX-RUTH__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 17,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_22_Collage-Restore-Night-Cream-2__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 18,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_41_BN2-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 19,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_30_BC3-GOOD__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 20,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_58_BC3-box__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 21,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_23_BN5__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 22,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_61_BN5-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 23,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_24_Moisture-Boost-Eye-Serum__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 24,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_42_BN4-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 25,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_4_BN3__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 26,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_43_BN3-box__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 27,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_89_Bonage-Laboratories-Wrinkle-Correct__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 28,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_32_BV1__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 29,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_54_Flash-Lift-Cream__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 30,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_50_NEW-BU7-BOX__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 31,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_102_NEW-BU7-FOR-WEBSITE__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 32,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_55_BG1-IMAGE-FOR-WEBSITE-GOOD__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 33,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_36_BG1-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 34,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_101_BG1-HOW-TO-OPEN__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 35,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_24_Moisture-Boost-Eye-Serum__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 36,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_42_BN4-box__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 37,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_50_Multi-Action-Instant-Lift-Solution-__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 38,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_46_-73A5233__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 39,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_103_BR3-HOW-TO-OPEN__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 40,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_39_Sculpting-Eye-Cream-2__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 41,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_44_BR1-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 42,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_37_Volumizing-Eye-Cream-2__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 43,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_45_BR2-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 44,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_66_Active-Repair-Beauty-Capsules-2__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 45,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_57_BU8-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 46,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_112_Capsules4__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 47,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_113_Capsules5-480-480__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 48,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_117_BU8-WEBIMAGE1__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 49,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_2_Age-Control-Firming-Cream-2__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 50,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_35_BU3-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 51,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_3_Age-Control-Firming-Serum-2__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 52,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_49_BU4-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 53,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_18_BU5__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 54,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_59_BU5-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 55,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_54_Flash-Lift-Cream__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 56,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_50_NEW-BU7-BOX__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 57,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_102_NEW-BU7-FOR-WEBSITE__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 58,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_19_BU6Goldfusioncleansingoil__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 59,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_16_BU1__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 60,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_47_BU1-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 61,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_17_BU2__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 62,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_48_BU2-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 63,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_35_75and-HYALURONIC-2__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 64,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_38_BL2-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 65,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_36_Boosting-Vitamin-Nectar-2__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 66,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_37_BL1-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 67,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_34_LINE-REDUCING-2__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 68,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_40_BL4-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 69,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_33_REPAIRING-HYALURONIC-ACID-2__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 70,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_39_BL3-box__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 71,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_50_Multi-Action-Instant-Lift-Solution-__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 72,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_46_-73A5233__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 73,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_103_BR3-HOW-TO-OPEN__c-max_w-530_h-480_q-100-1.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 74,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_39_Sculpting-Eye-Cream-2__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 75,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_44_BR1-box__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 76,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_37_Volumizing-Eye-Cream-2__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 77,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_45_BR2-box__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 78,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_55_BG1-IMAGE-FOR-WEBSITE-GOOD__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 79,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_36_BG1-box__c-max_w-530_h-480_q-100-1.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 80,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_101_BG1-HOW-TO-OPEN__c-max_w-530_h-480_q-100-1.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 81,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_10_BB1bHydraBoostBodybutter__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 82,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_133_BONAGE-NAIL-KIT-BB5-NEW-2023-MARCH__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 83,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_9_main-9-BB1ahydraboostbodybutterb__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 84,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_7_main7BB2bdualactionsaltscrub__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 85,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_9_main-9-BB1ahydraboostbodybutterb__c-max_w-288_h-288_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 86,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_13_handcream1__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 87,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_13_handcream1__c-max_w-288_h-288_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 88,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_1_main1BM2AftershaveCalmingcream__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 89,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_62_Homme__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 90,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_20_BM1Mineralrestorefaceandeye__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 91,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_49_73A9401__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 92,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_48_73A9377__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 93,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_43_73A9334__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 94,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_42_73A9332__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 95,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_41_73A9337__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 96,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_40_73A9316__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 97,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_45_73A9340__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 98,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_44_73A9352__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 99,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_47_73A9369__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 100,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_46_73A9363__c-max_w-530_h-480_q-100.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 101,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_62_Homme__c-max_w-530_h-480_q-1001.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 102,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_133_BONAGE-NAIL-KIT-BB5-NEW-2023-MARCH__c-max_w-530_h-480_q-1001.jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 103,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_64_EYE-AND-NECK-2__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 104,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_93_EYE-AND-NECK-1__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 105,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_63_RESIZED-FOR-WEBSITE-1__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 106,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_89_FACE-EYE-and-NECK-DEVICE-5__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 107,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//BG_main_90_FACE-EYE-and-NECK-DEVICE-6__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 108,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_61_WEBWHITENEW__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 109,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_58_WEBGREYNEW__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        },
                        new
                        {
                            FileId = 110,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FileName = "Resources//main_57_WEBPINKNEW__c-max_w-530_h-480_q-100.jpeg",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Database.Entitys.TbFileProduct", b =>
                {
                    b.Property<int>("FileProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileProductId"), 1L, 1);

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("FileProductId");

                    b.HasIndex("FileId");

                    b.HasIndex("ProductId");

                    b.ToTable("TbFileProduct");

                    b.HasData(
                        new
                        {
                            FileProductId = 1,
                            FileId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            FileProductId = 2,
                            FileId = 2,
                            ProductId = 2
                        },
                        new
                        {
                            FileProductId = 3,
                            FileId = 3,
                            ProductId = 2
                        },
                        new
                        {
                            FileProductId = 4,
                            FileId = 4,
                            ProductId = 3
                        },
                        new
                        {
                            FileProductId = 5,
                            FileId = 5,
                            ProductId = 3
                        },
                        new
                        {
                            FileProductId = 6,
                            FileId = 6,
                            ProductId = 4
                        },
                        new
                        {
                            FileProductId = 7,
                            FileId = 7,
                            ProductId = 4
                        },
                        new
                        {
                            FileProductId = 8,
                            FileId = 8,
                            ProductId = 5
                        },
                        new
                        {
                            FileProductId = 9,
                            FileId = 9,
                            ProductId = 6
                        },
                        new
                        {
                            FileProductId = 10,
                            FileId = 10,
                            ProductId = 6
                        },
                        new
                        {
                            FileProductId = 11,
                            FileId = 11,
                            ProductId = 7
                        },
                        new
                        {
                            FileProductId = 12,
                            FileId = 12,
                            ProductId = 7
                        },
                        new
                        {
                            FileProductId = 13,
                            FileId = 13,
                            ProductId = 8
                        },
                        new
                        {
                            FileProductId = 14,
                            FileId = 14,
                            ProductId = 8
                        },
                        new
                        {
                            FileProductId = 15,
                            FileId = 15,
                            ProductId = 9
                        },
                        new
                        {
                            FileProductId = 16,
                            FileId = 16,
                            ProductId = 9
                        },
                        new
                        {
                            FileProductId = 17,
                            FileId = 17,
                            ProductId = 10
                        },
                        new
                        {
                            FileProductId = 18,
                            FileId = 18,
                            ProductId = 10
                        },
                        new
                        {
                            FileProductId = 19,
                            FileId = 19,
                            ProductId = 11
                        },
                        new
                        {
                            FileProductId = 20,
                            FileId = 20,
                            ProductId = 11
                        },
                        new
                        {
                            FileProductId = 21,
                            FileId = 21,
                            ProductId = 12
                        },
                        new
                        {
                            FileProductId = 22,
                            FileId = 22,
                            ProductId = 12
                        },
                        new
                        {
                            FileProductId = 23,
                            FileId = 23,
                            ProductId = 13
                        },
                        new
                        {
                            FileProductId = 24,
                            FileId = 24,
                            ProductId = 13
                        },
                        new
                        {
                            FileProductId = 25,
                            FileId = 25,
                            ProductId = 14
                        },
                        new
                        {
                            FileProductId = 26,
                            FileId = 26,
                            ProductId = 14
                        },
                        new
                        {
                            FileProductId = 27,
                            FileId = 27,
                            ProductId = 15
                        },
                        new
                        {
                            FileProductId = 28,
                            FileId = 28,
                            ProductId = 15
                        },
                        new
                        {
                            FileProductId = 29,
                            FileId = 29,
                            ProductId = 16
                        },
                        new
                        {
                            FileProductId = 30,
                            FileId = 30,
                            ProductId = 16
                        },
                        new
                        {
                            FileProductId = 31,
                            FileId = 31,
                            ProductId = 16
                        },
                        new
                        {
                            FileProductId = 32,
                            FileId = 32,
                            ProductId = 17
                        },
                        new
                        {
                            FileProductId = 33,
                            FileId = 33,
                            ProductId = 17
                        },
                        new
                        {
                            FileProductId = 34,
                            FileId = 34,
                            ProductId = 17
                        },
                        new
                        {
                            FileProductId = 35,
                            FileId = 35,
                            ProductId = 18
                        },
                        new
                        {
                            FileProductId = 36,
                            FileId = 36,
                            ProductId = 18
                        },
                        new
                        {
                            FileProductId = 37,
                            FileId = 37,
                            ProductId = 19
                        },
                        new
                        {
                            FileProductId = 38,
                            FileId = 38,
                            ProductId = 19
                        },
                        new
                        {
                            FileProductId = 39,
                            FileId = 39,
                            ProductId = 19
                        },
                        new
                        {
                            FileProductId = 40,
                            FileId = 40,
                            ProductId = 20
                        },
                        new
                        {
                            FileProductId = 41,
                            FileId = 41,
                            ProductId = 20
                        },
                        new
                        {
                            FileProductId = 42,
                            FileId = 42,
                            ProductId = 21
                        },
                        new
                        {
                            FileProductId = 43,
                            FileId = 43,
                            ProductId = 21
                        },
                        new
                        {
                            FileProductId = 44,
                            FileId = 44,
                            ProductId = 22
                        },
                        new
                        {
                            FileProductId = 45,
                            FileId = 45,
                            ProductId = 22
                        },
                        new
                        {
                            FileProductId = 46,
                            FileId = 46,
                            ProductId = 22
                        },
                        new
                        {
                            FileProductId = 47,
                            FileId = 47,
                            ProductId = 22
                        },
                        new
                        {
                            FileProductId = 48,
                            FileId = 48,
                            ProductId = 22
                        },
                        new
                        {
                            FileProductId = 49,
                            FileId = 49,
                            ProductId = 23
                        },
                        new
                        {
                            FileProductId = 50,
                            FileId = 50,
                            ProductId = 23
                        },
                        new
                        {
                            FileProductId = 51,
                            FileId = 51,
                            ProductId = 24
                        },
                        new
                        {
                            FileProductId = 52,
                            FileId = 52,
                            ProductId = 24
                        },
                        new
                        {
                            FileProductId = 53,
                            FileId = 53,
                            ProductId = 25
                        },
                        new
                        {
                            FileProductId = 54,
                            FileId = 54,
                            ProductId = 25
                        },
                        new
                        {
                            FileProductId = 55,
                            FileId = 55,
                            ProductId = 26
                        },
                        new
                        {
                            FileProductId = 56,
                            FileId = 56,
                            ProductId = 26
                        },
                        new
                        {
                            FileProductId = 57,
                            FileId = 57,
                            ProductId = 26
                        },
                        new
                        {
                            FileProductId = 58,
                            FileId = 58,
                            ProductId = 27
                        },
                        new
                        {
                            FileProductId = 59,
                            FileId = 59,
                            ProductId = 28
                        },
                        new
                        {
                            FileProductId = 60,
                            FileId = 60,
                            ProductId = 28
                        },
                        new
                        {
                            FileProductId = 61,
                            FileId = 61,
                            ProductId = 29
                        },
                        new
                        {
                            FileProductId = 62,
                            FileId = 62,
                            ProductId = 29
                        },
                        new
                        {
                            FileProductId = 63,
                            FileId = 63,
                            ProductId = 30
                        },
                        new
                        {
                            FileProductId = 64,
                            FileId = 64,
                            ProductId = 30
                        },
                        new
                        {
                            FileProductId = 65,
                            FileId = 65,
                            ProductId = 31
                        },
                        new
                        {
                            FileProductId = 66,
                            FileId = 66,
                            ProductId = 31
                        },
                        new
                        {
                            FileProductId = 67,
                            FileId = 67,
                            ProductId = 32
                        },
                        new
                        {
                            FileProductId = 68,
                            FileId = 68,
                            ProductId = 32
                        },
                        new
                        {
                            FileProductId = 69,
                            FileId = 69,
                            ProductId = 33
                        },
                        new
                        {
                            FileProductId = 70,
                            FileId = 70,
                            ProductId = 33
                        },
                        new
                        {
                            FileProductId = 71,
                            FileId = 71,
                            ProductId = 34
                        },
                        new
                        {
                            FileProductId = 72,
                            FileId = 72,
                            ProductId = 34
                        },
                        new
                        {
                            FileProductId = 73,
                            FileId = 73,
                            ProductId = 34
                        },
                        new
                        {
                            FileProductId = 74,
                            FileId = 74,
                            ProductId = 35
                        },
                        new
                        {
                            FileProductId = 75,
                            FileId = 75,
                            ProductId = 35
                        },
                        new
                        {
                            FileProductId = 76,
                            FileId = 76,
                            ProductId = 36
                        },
                        new
                        {
                            FileProductId = 77,
                            FileId = 77,
                            ProductId = 36
                        },
                        new
                        {
                            FileProductId = 78,
                            FileId = 78,
                            ProductId = 37
                        },
                        new
                        {
                            FileProductId = 79,
                            FileId = 79,
                            ProductId = 37
                        },
                        new
                        {
                            FileProductId = 80,
                            FileId = 80,
                            ProductId = 37
                        },
                        new
                        {
                            FileProductId = 81,
                            FileId = 81,
                            ProductId = 38
                        },
                        new
                        {
                            FileProductId = 82,
                            FileId = 82,
                            ProductId = 39
                        },
                        new
                        {
                            FileProductId = 83,
                            FileId = 83,
                            ProductId = 40
                        },
                        new
                        {
                            FileProductId = 84,
                            FileId = 84,
                            ProductId = 41
                        },
                        new
                        {
                            FileProductId = 85,
                            FileId = 85,
                            ProductId = 42
                        },
                        new
                        {
                            FileProductId = 86,
                            FileId = 86,
                            ProductId = 43
                        },
                        new
                        {
                            FileProductId = 87,
                            FileId = 87,
                            ProductId = 44
                        },
                        new
                        {
                            FileProductId = 88,
                            FileId = 88,
                            ProductId = 45
                        },
                        new
                        {
                            FileProductId = 89,
                            FileId = 89,
                            ProductId = 46
                        },
                        new
                        {
                            FileProductId = 90,
                            FileId = 90,
                            ProductId = 47
                        },
                        new
                        {
                            FileProductId = 91,
                            FileId = 91,
                            ProductId = 48
                        },
                        new
                        {
                            FileProductId = 92,
                            FileId = 92,
                            ProductId = 49
                        },
                        new
                        {
                            FileProductId = 93,
                            FileId = 93,
                            ProductId = 50
                        },
                        new
                        {
                            FileProductId = 94,
                            FileId = 94,
                            ProductId = 51
                        },
                        new
                        {
                            FileProductId = 95,
                            FileId = 95,
                            ProductId = 52
                        },
                        new
                        {
                            FileProductId = 96,
                            FileId = 96,
                            ProductId = 53
                        },
                        new
                        {
                            FileProductId = 97,
                            FileId = 97,
                            ProductId = 54
                        },
                        new
                        {
                            FileProductId = 98,
                            FileId = 98,
                            ProductId = 55
                        },
                        new
                        {
                            FileProductId = 99,
                            FileId = 99,
                            ProductId = 56
                        },
                        new
                        {
                            FileProductId = 100,
                            FileId = 100,
                            ProductId = 57
                        },
                        new
                        {
                            FileProductId = 101,
                            FileId = 101,
                            ProductId = 58
                        },
                        new
                        {
                            FileProductId = 102,
                            FileId = 102,
                            ProductId = 59
                        },
                        new
                        {
                            FileProductId = 103,
                            FileId = 103,
                            ProductId = 60
                        },
                        new
                        {
                            FileProductId = 104,
                            FileId = 104,
                            ProductId = 60
                        },
                        new
                        {
                            FileProductId = 105,
                            FileId = 105,
                            ProductId = 61
                        },
                        new
                        {
                            FileProductId = 106,
                            FileId = 106,
                            ProductId = 61
                        },
                        new
                        {
                            FileProductId = 107,
                            FileId = 107,
                            ProductId = 61
                        },
                        new
                        {
                            FileProductId = 108,
                            FileId = 108,
                            ProductId = 62
                        },
                        new
                        {
                            FileProductId = 109,
                            FileId = 109,
                            ProductId = 63
                        },
                        new
                        {
                            FileProductId = 110,
                            FileId = 110,
                            ProductId = 64
                        });
                });

            modelBuilder.Entity("Database.Entitys.TbProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("ContentBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPromote")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductGroupId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductGroupId");

                    b.ToTable("TbProduct");
                });

            modelBuilder.Entity("Database.Entitys.TbProductGroup", b =>
                {
                    b.Property<int>("ProductGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductGroupId"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProductGroupDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductGroupId");

                    b.ToTable("TbProductGroup");

                    b.HasData(
                        new
                        {
                            ProductGroupId = 1,
                            CreateDate = new DateTime(2023, 12, 30, 13, 3, 38, 798, DateTimeKind.Utc).AddTicks(3777),
                            IsDeleted = false,
                            ProductGroupDescription = "<p>Soothe, tone and clear away impurities with our Flawless Cleansing range-designed to cleanse skin deeply, while still leaving it fully hydrated and silky smooth. Feel refreshed, clean and radiant with a range of products that remove oils, make up, dirt and dead skin. Experience truly purifying results through rich, nourishing ingredients that help you fall back in love with bare-faced beauty.</p>",
                            ProductGroupName = "FLAWLESS CLEANSING"
                        },
                        new
                        {
                            ProductGroupId = 2,
                            CreateDate = new DateTime(2023, 12, 30, 13, 3, 38, 798, DateTimeKind.Utc).AddTicks(3780),
                            IsDeleted = false,
                            ProductGroupDescription = "<p>The Classique collection of creams and masks has been formulated using an array of powerful ingredients to help target the signs of ageing, including matrixyl 3000-a solution that visibly reduces wrinkles and improves skin elasticity. The line features not only vitamins and luscious plant extracts, but also collagen, which works to restore the skin’s natural youthful complexion. Users will look and feel classically, effortlessly radiant.</p>",
                            ProductGroupName = "CLASSIQUE"
                        },
                        new
                        {
                            ProductGroupId = 3,
                            CreateDate = new DateTime(2023, 12, 30, 13, 3, 38, 798, DateTimeKind.Utc).AddTicks(3780),
                            IsDeleted = false,
                            ProductGroupDescription = "<p>The skin around the eyes is much thinner and less oily than the rest of our face, this is the reason it needs extra care and attention. Our innovative eye care collection is specially formulated for the delicate eye area to keep the eyes as beautiful as they are supposed to be.</p>",
                            ProductGroupName = "EYE CARE"
                        },
                        new
                        {
                            ProductGroupId = 4,
                            CreateDate = new DateTime(2023, 12, 30, 13, 3, 38, 798, DateTimeKind.Utc).AddTicks(3781),
                            IsDeleted = false,
                            ProductGroupDescription = "<p>Rich in innovative ingredients that soothe and nourish the skin, the Prestige collection features age-controlling products that reduce the visibility of lines and wrinkles. Prestige masks and serums leave the skin feeling totally refreshed, hydrated and moisturised-perfect for a luxurious spa-like home treatment. Enjoy vibrant, youthful-looking skin with total ease.</p>",
                            ProductGroupName = "PRESTIGE"
                        },
                        new
                        {
                            ProductGroupId = 5,
                            CreateDate = new DateTime(2023, 12, 30, 13, 3, 38, 798, DateTimeKind.Utc).AddTicks(3781),
                            IsDeleted = false,
                            ProductGroupDescription = "<p>A luxurious line of smoothing, hydrating and lifting treatments, Lumiere contains active ingredients that specifically target the visible signs of ageing. Hyaluronic acid, the powerful rehydrator, has been blended with matrixyl 3000, the age-defying solution that visibly improves skin tone, elasticity and structure. Lumiere also supplies the skin with natural vitamin combinations, helping to promote a younger and firmer appearance.</p>",
                            ProductGroupName = "LUMIÉRE"
                        },
                        new
                        {
                            ProductGroupId = 6,
                            CreateDate = new DateTime(2023, 12, 30, 13, 3, 38, 798, DateTimeKind.Utc).AddTicks(3782),
                            IsDeleted = false,
                            ProductGroupDescription = "<p>The Revive collection combines the latest innovations in eye care technology with active, anti-ageing ingredients that work gently on the delicate eye area. Among its plumping and hydrating ingredients, Revive contains VOLUFORM, the natural alternative for lipofilling. VOLUFORM works through multiple layers of the skin to fill lines and wrinkles and leave skin looking youthful and radiant.</p>",
                            ProductGroupName = "RÉVIVE"
                        },
                        new
                        {
                            ProductGroupId = 7,
                            CreateDate = new DateTime(2023, 12, 30, 13, 3, 38, 798, DateTimeKind.Utc).AddTicks(3782),
                            IsDeleted = false,
                            ProductGroupDescription = "",
                            ProductGroupName = "GENÉSE"
                        },
                        new
                        {
                            ProductGroupId = 8,
                            CreateDate = new DateTime(2023, 12, 30, 13, 3, 38, 798, DateTimeKind.Utc).AddTicks(3810),
                            IsDeleted = false,
                            ProductGroupDescription = "<p>Bonage offers your whole body the sumptuous feeling of complete cleanliness and natural nourishment. Enhance the skin's natural glow and leave it feeling soft, smooth, and pure all day long.</p>",
                            ProductGroupName = "BODY CARE"
                        },
                        new
                        {
                            ProductGroupId = 9,
                            CreateDate = new DateTime(2023, 12, 30, 13, 3, 38, 798, DateTimeKind.Utc).AddTicks(3811),
                            IsDeleted = false,
                            ProductGroupDescription = "<p>Specially created for men, Bonage HOMME is designed to support skin's natural health and hydration. Powerful active ingredients combine with state-of-the-art technology for unique formulas with maximum results.</p>",
                            ProductGroupName = "HOMME"
                        },
                        new
                        {
                            ProductGroupId = 10,
                            CreateDate = new DateTime(2023, 12, 30, 13, 3, 38, 798, DateTimeKind.Utc).AddTicks(3811),
                            IsDeleted = false,
                            ProductGroupDescription = "<p>Stand out with Bonage’s beautifully hand crafted, leather bags collection. Designed with the busy women in mind, our leather bags are made to be worn day, night and anywhere in between thanks to the functional details of each handbag. All our handbags are 100% Italian made, inspired by the latest fashion trends and crafted to perfection.</p>",
                            ProductGroupName = "LIMITED EDITION HANDBAGS"
                        },
                        new
                        {
                            ProductGroupId = 11,
                            CreateDate = new DateTime(2023, 12, 30, 13, 3, 38, 798, DateTimeKind.Utc).AddTicks(3812),
                            IsDeleted = false,
                            ProductGroupDescription = "",
                            ProductGroupName = "SETS & GIFTS"
                        });
                });

            modelBuilder.Entity("Database.Entitys.TbUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("TbUser");
                });

            modelBuilder.Entity("Database.Entitys.TbFileProduct", b =>
                {
                    b.HasOne("Database.Entitys.TbFile", "TbFile")
                        .WithMany("TbFileProducts")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entitys.TbProduct", "TbProduct")
                        .WithMany("TbFileProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TbFile");

                    b.Navigation("TbProduct");
                });

            modelBuilder.Entity("Database.Entitys.TbProduct", b =>
                {
                    b.HasOne("Database.Entitys.TbProductGroup", "TbProductGroup")
                        .WithMany("TbProducts")
                        .HasForeignKey("ProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TbProductGroup");
                });

            modelBuilder.Entity("Database.Entitys.TbFile", b =>
                {
                    b.Navigation("TbFileProducts");
                });

            modelBuilder.Entity("Database.Entitys.TbProduct", b =>
                {
                    b.Navigation("TbFileProducts");
                });

            modelBuilder.Entity("Database.Entitys.TbProductGroup", b =>
                {
                    b.Navigation("TbProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
